import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import NavbarWrapper from "@/components/shared/Navbar/NavbarWrapper";
import NextAuthProvider from "@/provider/NextAuthProvider";
  import { ToastContainer, toast } from 'react-toastify';
import TanStackQueryProvider from "@/provider/TanStackQueryProvider";
import CustomCursor from "@/components/CustomCursor/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "LogeAchi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // NextAuthProvider use for user
  
      <html lang="en" className={`${poppins.className} h-full antialiased`}>
        {/* use for data fetach Delete */}
       
        
         <body className="min-h-full flex flex-col bg-[#0f172a]">
          {/* custome cursor setup done */}
          <CustomCursor/>
            <NextAuthProvider>
         <TanStackQueryProvider>
            <ToastContainer />
          <NavbarWrapper />
       
          <main>{children}</main>

          </TanStackQueryProvider>
          </NextAuthProvider>
        </body>
     
      
      </html>
   
  );
}
