import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import NavbarWrapper from "@/components/shared/Navbar/NavbarWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.className} h-full antialiased`}
    >
 
      <body className="min-h-full flex flex-col">
             <NavbarWrapper/>
        <main>{children}</main>
      </body>
    </html>
  );
}
